In [1]:
import torch, numpy as np
import pandas as pd
from torch.utils.data.sampler import SubsetRandomSampler
import pickle

In [2]:
from utils_Tadpole import TadpoleSet
tp = TadpoleSet('TADPOLE_D1_D2.csv')

In [3]:
tp.predictors.shape

(8904, 20)

In [4]:
tp.labels

array([0, 1, 1, ..., 0, 2, 2])

In [5]:
tp.labnames

Index(['NL', 'Dementia', 'MCI'], dtype='object')

In [6]:
print (tp.predictors[:, tp.prednames.index('APOE4')])

[0. 1. 1. ... 0. 0. 1.]


In [7]:
tp.predictors[0, :]

array([7.43000e+01, 0.00000e+00, 1.36926e+00, 1.11370e+00, 0.00000e+00,
       1.06700e+01, 1.86700e+01, 2.80000e+01, 4.40000e+01, 8.33600e+03,
       1.22974e+06, 4.17700e+03, 2.79360e+04, 1.82350e+03, 6.32000e+02,
       1.94100e+03, 6.47000e+02, 8.33000e+02, 2.64400e+02, 2.44500e+01],
      dtype=float32)

In [8]:
len(tp)

8904

In [9]:
# Dividir de forma reproducible los datos en entrenamiento, validación y test
torch.manual_seed(1559224552)
size = len(tp)
train_size = int(0.8*size)
val_size = int(0.1*size)
test_size = size - (train_size + val_size)
train_dataset, val_dataset, test_dataset = torch.utils.data.random_split(tp, [train_size, val_size, test_size])
len(train_dataset), len(val_dataset), len(test_dataset)

(7123, 890, 891)

In [10]:
# Crear cargadores para los datos
batch_size = 64
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                          batch_size=batch_size,
                                          )
val_loader = torch.utils.data.DataLoader(dataset=val_dataset,
                                          batch_size=batch_size,
                                          )
test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          )

In [12]:
# Guardar los cargadores en disco
with open('loaders', 'wb') as f:
    pickle.dump((train_loader, val_loader, test_loader), f)